package Vista;

import Modelo.Cliente;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.net.Socket;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.JOptionPane.*;
import javax.swing.border.EmptyBorder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Santiago Baron Zuleta, Mauricio Sanchez, Sebastian Yepes
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActivos = new javax.swing.JList<>();
        butPrivado = new javax.swing.JToggleButton();
        users_conected = new javax.swing.JLabel();
        txtMensage = new javax.swing.JTextField();
        butEnviar = new javax.swing.JButton();
        nombreGrandeUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1135, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 1200));

        jPanel2.setBackground(new java.awt.Color(18, 26, 47));
        jPanel2.setMinimumSize(new java.awt.Dimension(1120, 691));

        jPanel1.setBackground(new java.awt.Color(13, 19, 35));

        salir.setBackground(new java.awt.Color(102, 16, 242));
        salir.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Cerrar sesión");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        lstActivos.setBackground(new java.awt.Color(23, 25, 55));
        lstActivos.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lstActivos.setForeground(new java.awt.Color(255, 255, 255));
        lstActivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstActivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstActivos.setDragEnabled(true);
        lstActivos.setFixedCellHeight(35);
        lstActivos.setName(""); // NOI18N
        jScrollPane2.setViewportView(lstActivos);

        butPrivado.setBackground(new java.awt.Color(102, 16, 242));
        butPrivado.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        butPrivado.setForeground(new java.awt.Color(255, 255, 255));
        butPrivado.setText("Privado");
        butPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrivadoActionPerformed(evt);
            }
        });

        users_conected.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        users_conected.setForeground(new java.awt.Color(255, 255, 255));
        users_conected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users_conected.setText("Usuarios conectados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butPrivado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(users_conected, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(users_conected)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butPrivado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        txtMensage.setBackground(new java.awt.Color(102, 102, 102));
        txtMensage.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtMensage.setForeground(new java.awt.Color(255, 255, 255));
        txtMensage.setMargin(new java.awt.Insets(0, 20, 0, 0));
        txtMensage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensageActionPerformed(evt);
            }
        });

        butEnviar.setBackground(new java.awt.Color(52, 128, 101));
        butEnviar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        butEnviar.setForeground(new java.awt.Color(255, 255, 255));
        butEnviar.setText("Enviar");
        butEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEnviarActionPerformed(evt);
            }
        });

        nombreGrandeUser.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        nombreGrandeUser.setForeground(new java.awt.Color(255, 255, 255));
        nombreGrandeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreGrandeUser.setText("Nombre");

        panMostrar.setEditable(false);
        panMostrar.setBackground(new java.awt.Color(23, 25, 55));
        panMostrar.setColumns(20);
        panMostrar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        panMostrar.setForeground(new java.awt.Color(255, 255, 255));
        panMostrar.setRows(5);
        panMostrar.setCaretColor(new java.awt.Color(23, 25, 55));
        panMostrar.setMargin(new java.awt.Insets(20, 20, 20, 20));
        panMostrar.setMinimumSize(new java.awt.Dimension(21, 36));
        jScrollPane1.setViewportView(panMostrar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombreGrandeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(nombreGrandeUser)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtMensage))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Vector<String> nomUsers;
    VentanaPrivada ventPrivada;
    Cliente cliente;
    public String user_name;

    private void butEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEnviarActionPerformed
        String mensaje = txtMensage.getText();
        cliente.flujo(mensaje);
        txtMensage.setText("");
    }//GEN-LAST:event_butEnviarActionPerformed

    private void txtMensageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensageActionPerformed
        String mensaje = txtMensage.getText();
        cliente.flujo(mensaje);
        txtMensage.setText("");
    }//GEN-LAST:event_txtMensageActionPerformed

    private void butPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrivadoActionPerformed
        int pos = this.lstActivos.getSelectedIndex();
        if (pos >= 0) {
            ventPrivada.setAmigo(nomUsers.get(pos));
            ventPrivada.setVisible(true);
        }
    }//GEN-LAST:event_butPrivadoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        cliente.flujo("El cliente " + user_name + " se ha desconectado...");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    public void enviarMensaje(String mensaje) {
        cliente.flujo(mensaje);
    }

    public JTextField getTxtMensage() {
        return txtMensage;
    }

    public void setTxtMensage(JTextField txtMensage) {
        this.txtMensage = txtMensage;
    }

    public void actualizarChats(Vector datos) {
        nomUsers = datos;
        lstActivos.remove(0);
        ponerDatosList(this.lstActivos, nomUsers);
    }

    public void setNombreUser(String user) {
        nombreGrandeUser.setText("Chat general de " + user);
    }

    public void mostrarMsg(String msg) {
        this.panMostrar.append(msg + "\n\n\n");
    }

    public void ponerActivos(Vector datos) {
        cambiarNumero(datos);
        nomUsers = datos;
        ponerDatosList(this.lstActivos, nomUsers);
    }

    public void cambiarNumero(Vector datos) {
        this.users_conected.setText("Hay " + datos.size() + " usuarios conectados");
    }

    public void agregarUser(String user) {
        nomUsers.add(user);
        cambiarNumero(nomUsers);
        ponerDatosList(this.lstActivos, nomUsers);
    }

    public void retirraUser(String user) {
        nomUsers.remove(user);
        ponerDatosList(this.lstActivos, nomUsers);
    }

    private void ponerDatosList(JList list, final Vector datos) {
        list.setModel(new AbstractListModel() {
            @Override
            public int getSize() {
                return datos.size();
            }

            @Override
            public Object getElementAt(int i) {
                return datos.get(i);
            }
        });
    }

    // ACÁ HAY QUE ARREGLAR--------------
    public void bloqueo(String user) {
        this.txtMensage.setEnabled(false);
    }
    //-----------------------------

    public void mensageAmigo(String amigo, String msg) {
        ventPrivada.setAmigo(amigo);
        ventPrivada.mostrarMsg(msg);
        ventPrivada.setVisible(true);
    }

    public void bloquear() {
        this.butEnviar.setEnabled(false);
        this.txtMensage.setEnabled(false);
    }

    public VentanaCliente(String user) throws IOException {

        initComponents();
        this.setTitle("Ventana cliente - " + user);

        user_name = user;

        cliente = new Cliente(this);
        cliente.conexion(user);

        Vector<String> prueba = new Vector();
        prueba = cliente.pedirUsuarios();

        int contador = 0;

        for (int i = 0; i < prueba.size(); i++) {
            if (prueba.get(i).equals(user)) {
                contador++;
            }
        }

        if (contador > 1) {
            JOptionPane.showMessageDialog(null, "El usuario ya esta conectado");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Bienvenid@ " + user);
            nomUsers = new Vector();
            ponerActivos(cliente.pedirUsuarios());
            ventPrivada = new VentanaPrivada(cliente);

            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            setVisible(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton butEnviar;
    public javax.swing.JToggleButton butPrivado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> lstActivos;
    public javax.swing.JLabel nombreGrandeUser;
    public javax.swing.JTextArea panMostrar;
    public javax.swing.JButton salir;
    public javax.swing.JTextField txtMensage;
    private javax.swing.JLabel users_conected;
    // End of variables declaration//GEN-END:variables

}
